-- migrations/065_sfaf_field_registry.sql
-- Categories, field definitions, and required field config for full SFAF Codes manager

-- =========================================================
-- sfaf_field_categories
-- =========================================================
CREATE TABLE IF NOT EXISTS sfaf_field_categories (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name        VARCHAR(100) NOT NULL,
    sort_order  INT NOT NULL DEFAULT 0,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO sfaf_field_categories (name, sort_order) VALUES
    ('Administrative Data', 10),
    ('Emission Characteristics', 20),
    ('Time/Date Information', 30),
    ('Organizational Information', 40),
    ('TX Location Data', 50),
    ('Space Stations (TX)', 60),
    ('TX Equipment', 70),
    ('TX Antenna Data', 80),
    ('RX Location Data', 90),
    ('Space Stations (RX)', 100),
    ('RX Equipment', 110),
    ('RX Antenna Data', 120),
    ('Supplementary Details', 130),
    ('Other Assignment IDs', 140),
    ('Additional Information', 150);

-- =========================================================
-- sfaf_field_definitions
-- =========================================================
CREATE TABLE IF NOT EXISTS sfaf_field_definitions (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    field_number            VARCHAR(10) NOT NULL UNIQUE,
    title                   VARCHAR(200) NOT NULL,
    category_id             UUID REFERENCES sfaf_field_categories(id) ON DELETE SET NULL,
    spectrum_xxi_tags       VARCHAR(100),
    gmf_tags                VARCHAR(200),
    max_input_length        VARCHAR(50),
    max_occurrences         VARCHAR(20),
    to_irac                 VARCHAR(10),
    max_chars_per_occurrence INT,
    max_chars_per_line      INT,
    has_lookup              BOOLEAN NOT NULL DEFAULT false,
    sort_order              INT NOT NULL DEFAULT 0,
    notes                   TEXT,
    is_active               BOOLEAN NOT NULL DEFAULT true,
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO sfaf_field_definitions
    (field_number, title, category_id, spectrum_xxi_tags, gmf_tags, max_input_length, max_occurrences, to_irac, has_lookup, sort_order)
VALUES
    ('005', 'Security Classification', (SELECT id FROM sfaf_field_categories WHERE name = 'Administrative Data' LIMIT 1), 'CLA,CDD,FOIm', 'CLA, CDD, FOIc', '2,10', '1', 'Y', false, 10),
    ('006', 'Security Classification Modification', (SELECT id FROM sfaf_field_categories WHERE name = 'Administrative Data' LIMIT 1), 'CLA,CDD,FOIm', 'CLA, CDD, FOIc', '2,10', '1', 'Y', false, 20),
    ('007', 'Missing Data Indicator', (SELECT id FROM sfaf_field_categories WHERE name = 'Administrative Data' LIMIT 1), 'MSD', 'MSD', '1', '1', 'Y', false, 30),
    ('010', 'Type of Action', (SELECT id FROM sfaf_field_categories WHERE name = 'Administrative Data' LIMIT 1), 'TYP', 'TYP', '1', '1', 'Y', true, 40),
    ('013', 'Declassification Instruction Comment', (SELECT id FROM sfaf_field_categories WHERE name = 'Administrative Data' LIMIT 1), 'DIC', '*DIC', '35', '1', 'Y', false, 50),
    ('014', 'Derivative Classification Authority', (SELECT id FROM sfaf_field_categories WHERE name = 'Administrative Data' LIMIT 1), 'CLF', '*CLFb', '8,60', '10', 'Y35', false, 60),
    ('015', 'Unclassified Data Fields', (SELECT id FROM sfaf_field_categories WHERE name = 'Administrative Data' LIMIT 1), 'CLU', '*CLUb', '72', '1', 'Y35', false, 70),
    ('016', 'Extended Declassification Date', (SELECT id FROM sfaf_field_categories WHERE name = 'Administrative Data' LIMIT 1), 'CDE', '*CDEb', '35', '1', 'Y', false, 80),
    ('017', 'Downgrading Instructions', (SELECT id FROM sfaf_field_categories WHERE name = 'Administrative Data' LIMIT 1), 'DNG', '*AGN,DNGb', '1,8', '1', 'Y', false, 90),
    ('018', 'Original Classification Authority', (SELECT id FROM sfaf_field_categories WHERE name = 'Administrative Data' LIMIT 1), 'OCA', '*CLAb', '60', '1', 'Y35', false, 100),
    ('019', 'Reason for Classification', (SELECT id FROM sfaf_field_categories WHERE name = 'Administrative Data' LIMIT 1), 'CLR', '*CLRb', '35', '1', 'Y', false, 110),
    ('020', 'Proposal References', (SELECT id FROM sfaf_field_categories WHERE name = 'Administrative Data' LIMIT 1), NULL, NULL, '64', '10', 'N', false, 120),
    ('102', 'Agency Serial Number', (SELECT id FROM sfaf_field_categories WHERE name = 'Administrative Data' LIMIT 1), 'SER', 'SER', '10', '1', 'Y', false, 130),
    ('103', 'IRAC Docket Number', (SELECT id FROM sfaf_field_categories WHERE name = 'Administrative Data' LIMIT 1), 'AUS', 'AUS', '8', '10', 'Ni', false, 140),
    ('105', 'List Serial Number', (SELECT id FROM sfaf_field_categories WHERE name = 'Administrative Data' LIMIT 1), 'LSN', 'LSR', '10', '1', 'Y', false, 150),
    ('106', 'Serial Replaced, Delete Date', (SELECT id FROM sfaf_field_categories WHERE name = 'Administrative Data' LIMIT 1), 'SRS,SEX', 'SRS,SEX', '10,8', '1', 'Y', false, 160),
    ('107', 'Authorization Date', (SELECT id FROM sfaf_field_categories WHERE name = 'Administrative Data' LIMIT 1), 'AUD', 'AUD', '8', '1', 'Ni', false, 170),
    ('108', 'Docket Numbers of Older Authorizations', (SELECT id FROM sfaf_field_categories WHERE name = 'Administrative Data' LIMIT 1), 'DOC', '*DOCb', '35', '30', 'Y', false, 180),
    ('110', 'Frequency(ies)', (SELECT id FROM sfaf_field_categories WHERE name = 'Emission Characteristics' LIMIT 1), 'FRQ,FRU', 'FRQ,*FRBb', '11,11-11, 11(11)', '1', 'Y', false, 190),
    ('111', 'Excluded Frequency Band', (SELECT id FROM sfaf_field_categories WHERE name = 'Emission Characteristics' LIMIT 1), 'FBE', '*FBEb', '23', '30', 'Y', false, 200),
    ('112', 'Frequency Separation Criteria', (SELECT id FROM sfaf_field_categories WHERE name = 'Emission Characteristics' LIMIT 1), NULL, NULL, '35', '1', 'N', false, 210),
    ('113', 'Station Class', (SELECT id FROM sfaf_field_categories WHERE name = 'Emission Characteristics' LIMIT 1), 'STC', 'STC', '4', '20', 'Y', false, 220),
    ('114', 'Emission Designator', (SELECT id FROM sfaf_field_categories WHERE name = 'Emission Characteristics' LIMIT 1), 'EMS', 'EMS', '11', '20', 'Y', false, 230),
    ('115', 'Transmitter Power', (SELECT id FROM sfaf_field_categories WHERE name = 'Emission Characteristics' LIMIT 1), 'PWR', 'PWR', '9', '20', 'Y', false, 240),
    ('116', 'Power Type', (SELECT id FROM sfaf_field_categories WHERE name = 'Emission Characteristics' LIMIT 1), NULL, NULL, '1', '20', 'N', false, 250),
    ('117', 'Effective Radiated Power', (SELECT id FROM sfaf_field_categories WHERE name = 'Emission Characteristics' LIMIT 1), NULL, NULL, '6', '20', 'N', false, 260),
    ('118', 'Power/ERP Augmentation', (SELECT id FROM sfaf_field_categories WHERE name = 'Emission Characteristics' LIMIT 1), NULL, NULL, '1', '20', 'N', false, 270),
    ('130', 'Time', (SELECT id FROM sfaf_field_categories WHERE name = 'Time/Date Information' LIMIT 1), 'TME', 'TME', '4', '1', 'Y', false, 280),
    ('131', 'Percent Time', (SELECT id FROM sfaf_field_categories WHERE name = 'Time/Date Information' LIMIT 1), NULL, NULL, '2', '1', 'N', false, 290),
    ('140', 'Required Date', (SELECT id FROM sfaf_field_categories WHERE name = 'Time/Date Information' LIMIT 1), NULL, NULL, '8', '1', 'N', false, 300),
    ('141', 'Expiration Date', (SELECT id FROM sfaf_field_categories WHERE name = 'Time/Date Information' LIMIT 1), 'EXD', 'EXD', '8', '1', 'Y', false, 310),
    ('142', 'Review Date', (SELECT id FROM sfaf_field_categories WHERE name = 'Time/Date Information' LIMIT 1), NULL, NULL, '8', '1', 'N', false, 320),
    ('143', 'Revision Date', (SELECT id FROM sfaf_field_categories WHERE name = 'Time/Date Information' LIMIT 1), 'RVD', 'RVD', '8', '1', 'Ni', false, 330),
    ('144', 'Approval Authority Indicator', (SELECT id FROM sfaf_field_categories WHERE name = 'Time/Date Information' LIMIT 1), NULL, NULL, '1', '1', 'N', true, 340),
    ('145', 'ITU BR Registration', (SELECT id FROM sfaf_field_categories WHERE name = 'Time/Date Information' LIMIT 1), NULL, NULL, '1,20', '1', 'N', false, 350),
    ('146', 'DCS Trunk ID', (SELECT id FROM sfaf_field_categories WHERE name = 'Time/Date Information' LIMIT 1), NULL, NULL, '6', '20', 'N', false, 360),
    ('147', 'Joint Agencies', (SELECT id FROM sfaf_field_categories WHERE name = 'Time/Date Information' LIMIT 1), 'JNT', '*JNTb', '4', '20', 'Y', false, 370),
    ('151', 'Coordination Indicator', (SELECT id FROM sfaf_field_categories WHERE name = 'Time/Date Information' LIMIT 1), 'ICI', 'ICI', '1', '1', 'Y', true, 380),
    ('152', 'Coordination Data', (SELECT id FROM sfaf_field_categories WHERE name = 'Time/Date Information' LIMIT 1), 'CAN,MEX,US A', '*CANb, *MEXb', '1,35', '30', 'Y', false, 390),
    ('200', 'Agency', (SELECT id FROM sfaf_field_categories WHERE name = 'Organizational Information' LIMIT 1), NULL, NULL, '6', '1', 'N', true, 400),
    ('201', 'Unified Command', (SELECT id FROM sfaf_field_categories WHERE name = 'Organizational Information' LIMIT 1), NULL, NULL, '8', '10', 'N', true, 410),
    ('202', 'Unified Command Service', (SELECT id FROM sfaf_field_categories WHERE name = 'Organizational Information' LIMIT 1), NULL, NULL, '8', '10', 'N', true, 420),
    ('203', 'Bureau', (SELECT id FROM sfaf_field_categories WHERE name = 'Organizational Information' LIMIT 1), 'BUR', 'BUR', '4', '1', 'Ye', true, 430),
    ('204', 'Command', (SELECT id FROM sfaf_field_categories WHERE name = 'Organizational Information' LIMIT 1), NULL, NULL, '18', '1', 'N', true, 440),
    ('205', 'Subcommand', (SELECT id FROM sfaf_field_categories WHERE name = 'Organizational Information' LIMIT 1), NULL, NULL, '18', '1', 'N', true, 450),
    ('206', 'Installation Frequency Manager', (SELECT id FROM sfaf_field_categories WHERE name = 'Organizational Information' LIMIT 1), NULL, NULL, '18', '1', 'N', true, 460),
    ('207', 'Operating Unit', (SELECT id FROM sfaf_field_categories WHERE name = 'Organizational Information' LIMIT 1), NULL, NULL, '18', '10', 'N', false, 470),
    ('208', 'User Net/Code', (SELECT id FROM sfaf_field_categories WHERE name = 'Organizational Information' LIMIT 1), 'NET', 'NET', '6', '1', 'Y5d', false, 480),
    ('209', 'Area AFC/DoD AFC/ Other Organizations', (SELECT id FROM sfaf_field_categories WHERE name = 'Organizational Information' LIMIT 1), NULL, NULL, '18', '10', 'N', true, 490),
    ('300', 'State/Country', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Location Data' LIMIT 1), 'XSC', 'XSC', '4', '1', 'Y', true, 500),
    ('301', 'Antenna Location', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Location Data' LIMIT 1), 'XAL', 'XAL', '24', '1', 'Y', false, 510),
    ('302', 'Station Control', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Location Data' LIMIT 1), 'XRC', 'XRC', '18', '1', 'Y8', false, 520),
    ('303', 'Antenna Coordinates', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Location Data' LIMIT 1), 'XLA XLG', 'XLA XLG', '15', '1', 'Y', false, 530),
    ('304', 'Call Sign', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Location Data' LIMIT 1), 'XCL', 'XCL', '10', '1', 'Y8', false, 540),
    ('306', 'Authorized Radius', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Location Data' LIMIT 1), 'XRD', '*RADb', '5', '1', 'Y', false, 550),
    ('315', 'Equatorial Inclination Angle', (SELECT id FROM sfaf_field_categories WHERE name = 'Space Stations (TX)' LIMIT 1), 'XIN', '*ORBb', '4', '1', 'Y', false, 560),
    ('316', 'Apogee', (SELECT id FROM sfaf_field_categories WHERE name = 'Space Stations (TX)' LIMIT 1), 'XAE', '*ORBb', '5', '1', 'Y', false, 570),
    ('317', 'Perigee', (SELECT id FROM sfaf_field_categories WHERE name = 'Space Stations (TX)' LIMIT 1), 'XPE', '*ORBb', '5', '1', 'Y', false, 580),
    ('318', 'Period of Orbit', (SELECT id FROM sfaf_field_categories WHERE name = 'Space Stations (TX)' LIMIT 1), 'XPD', '*ORBb', '7', '1', 'Y', false, 590),
    ('319', 'Number of Satellites', (SELECT id FROM sfaf_field_categories WHERE name = 'Space Stations (TX)' LIMIT 1), 'XNR', '*ORBb', '2', '1', 'Y', false, 600),
    ('321', 'Power Density', (SELECT id FROM sfaf_field_categories WHERE name = 'Space Stations (TX)' LIMIT 1), 'SPD', 'SPD', '4', '1', 'Y', false, 610),
    ('340', 'Equipment Nomenclature', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Equipment' LIMIT 1), 'XEQ', '*EQTb', '1,18', '10', 'Y', false, 620),
    ('341', 'Number of Stations, System Name', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Equipment' LIMIT 1), 'NTT,NAM', '*NRMb', '5,29', '3', 'Y', false, 630),
    ('342', 'Aircraft Nautical Mile Value', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Equipment' LIMIT 1), 'XNM', '*RADb', '4', '1', 'N', false, 640),
    ('343', 'Equipment Certification Identification Number', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Equipment' LIMIT 1), NULL, '*AGN,JFAb', '15', '10', 'Y', false, 650),
    ('344', 'Off-the-shelf Equipment', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Equipment' LIMIT 1), 'EQS', '*EQSb', '6', '10', 'Y', false, 660),
    ('345', 'Radar Tunability', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Equipment' LIMIT 1), 'TUN', '*EQTb', '2', '1', 'Y', false, 670),
    ('346', 'Pulse Duration', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Equipment' LIMIT 1), 'PDD', '*EQTb', '9, 9-9', '30', 'Y', false, 680),
    ('347', 'Pulse Repetition Rate', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Equipment' LIMIT 1), 'PRR', '*PRRb', '9, 9-9', '30', 'Y', false, 690),
    ('348', 'Intermediate Frequency', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Equipment' LIMIT 1), NULL, NULL, '11', '1', 'N', false, 700),
    ('349', 'Sidelobe Suppression', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Equipment' LIMIT 1), NULL, NULL, '1', '1', 'N', false, 710),
    ('354', 'Antenna Name', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Antenna Data' LIMIT 1), 'XAT', 'XAD', '10', '10', 'Y', true, 720),
    ('355', 'Antenna Nomenclature', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Antenna Data' LIMIT 1), 'XAK', '*EQTb', '18', '10', 'Y', false, 730),
    ('356', 'Antenna Structure Height', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Antenna Data' LIMIT 1), NULL, NULL, '3', '10', 'N', false, 740),
    ('357', 'Antenna Gain', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Antenna Data' LIMIT 1), 'XAG', 'XAD,*EGNb , *SGNb', '4', '10', 'Y', false, 750),
    ('358', 'Antenna Elevation', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Antenna Data' LIMIT 1), 'XSE', 'XAD', '5', '10', 'Y', false, 760),
    ('359', 'Antenna Feedpoint Height', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Antenna Data' LIMIT 1), 'XAH', 'XAD', '5', '10', 'Y', false, 770),
    ('360', 'Antenna Horizontal Beamwidth', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Antenna Data' LIMIT 1), 'XBW', 'XAD,*EBW b,*SBWb', '4', '10', 'Y', false, 780),
    ('361', 'Antenna Vertical Beamwidth', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Antenna Data' LIMIT 1), NULL, NULL, '3', '10', 'N', false, 790),
    ('362', 'Anenna Orientation', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Antenna Data' LIMIT 1), 'XAZ', 'XAZ, XAD', '3,3-3', '10', 'Y', false, 800),
    ('363', 'Antenna Polarization', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Antenna Data' LIMIT 1), 'XAP', 'XAP', '1', '10', 'Y', true, 810),
    ('373', 'JSC Area Code', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Antenna Data' LIMIT 1), NULL, NULL, '1', '1', 'N', false, 820),
    ('374', 'ITU Region', (SELECT id FROM sfaf_field_categories WHERE name = 'TX Antenna Data' LIMIT 1), NULL, NULL, '1', '1', 'N', false, 830),
    ('400', 'State/Country', (SELECT id FROM sfaf_field_categories WHERE name = 'RX Location Data' LIMIT 1), 'RSC', 'RSC', '4', '1', 'Y', true, 840),
    ('401', 'Antenna Location', (SELECT id FROM sfaf_field_categories WHERE name = 'RX Location Data' LIMIT 1), 'RAL', 'RAL', '24', '1', 'Y', false, 850),
    ('402', 'Receiver Control', (SELECT id FROM sfaf_field_categories WHERE name = 'RX Location Data' LIMIT 1), 'RRC', 'RRC', '18', '1', 'Y8', false, 860),
    ('403', 'Antenna Coordinates', (SELECT id FROM sfaf_field_categories WHERE name = 'RX Location Data' LIMIT 1), 'RLA RLG', 'RLA RLG', '15', '1', 'Y', false, 870),
    ('404', 'Call Sign', (SELECT id FROM sfaf_field_categories WHERE name = 'RX Location Data' LIMIT 1), 'RCL', 'ACL', '10', '1', 'Y8', false, 880),
    ('406', 'Authorized Radius', (SELECT id FROM sfaf_field_categories WHERE name = 'RX Location Data' LIMIT 1), 'RRD', '*RADb', '4', '1', 'Y', false, 890),
    ('407', 'Path Length', (SELECT id FROM sfaf_field_categories WHERE name = 'RX Location Data' LIMIT 1), NULL, NULL, '5', '1', 'N', false, 900),
    ('408', 'Repeater Indicator', (SELECT id FROM sfaf_field_categories WHERE name = 'RX Location Data' LIMIT 1), 'RPT', '*RPTb', '1', '1', 'Y', false, 910),
    ('415', 'Equatorial Inclination Angle', (SELECT id FROM sfaf_field_categories WHERE name = 'Space Stations (RX)' LIMIT 1), 'RIN', '*ORBb', '4', '1', 'Y', false, 920),
    ('416', 'Apogee', (SELECT id FROM sfaf_field_categories WHERE name = 'Space Stations (RX)' LIMIT 1), 'RAE', '*ORBb', '5', '1', 'Y', false, 930),
    ('417', 'Perigee', (SELECT id FROM sfaf_field_categories WHERE name = 'Space Stations (RX)' LIMIT 1), 'RPE', '*ORBb', '5', '1', 'Y', false, 940),
    ('418', 'Period of Orbit', (SELECT id FROM sfaf_field_categories WHERE name = 'Space Stations (RX)' LIMIT 1), 'RPD', '*ORBb', '7', '1', 'Y', false, 950),
    ('419', 'Number of Satellites', (SELECT id FROM sfaf_field_categories WHERE name = 'Space Stations (RX)' LIMIT 1), 'RNR', '*ORBb', '2', '1', 'Y', false, 960),
    ('440', 'Equipment Nomenclature', (SELECT id FROM sfaf_field_categories WHERE name = 'RX Equipment' LIMIT 1), 'REQ', '*EQRb', '1,18', '10', 'Y', false, 970),
    ('442', 'Aircraft Nautical Mile Value', (SELECT id FROM sfaf_field_categories WHERE name = 'RX Equipment' LIMIT 1), 'RNM', '*RADb', '4', '1', 'Ni', false, 980),
    ('443', 'Equipment Certification Identification Number', (SELECT id FROM sfaf_field_categories WHERE name = 'RX Equipment' LIMIT 1), NULL, NULL, '15', '10', 'N', false, 990),
    ('454', 'Antenna Name', (SELECT id FROM sfaf_field_categories WHERE name = 'RX Antenna Data' LIMIT 1), 'RAT', 'RAD', '10', '10', 'Y', false, 1000),
    ('455', 'Antenna Nomenclature', (SELECT id FROM sfaf_field_categories WHERE name = 'RX Antenna Data' LIMIT 1), 'RAK', '*EQRb', '18', '10', 'Y', false, 1010),
    ('456', 'Antenna Structure Height', (SELECT id FROM sfaf_field_categories WHERE name = 'RX Antenna Data' LIMIT 1), NULL, NULL, '3', '10', 'N', false, 1020),
    ('457', 'Antenna Gain', (SELECT id FROM sfaf_field_categories WHERE name = 'RX Antenna Data' LIMIT 1), 'RAG', 'RAD,*SGNb ,*EGNb', '4', '10', 'Y', false, 1030),
    ('458', 'Antenna Elevation', (SELECT id FROM sfaf_field_categories WHERE name = 'RX Antenna Data' LIMIT 1), 'RSE', 'RAD', '5', '10', 'Y', false, 1040),
    ('459', 'Antenna Feedpoint Height', (SELECT id FROM sfaf_field_categories WHERE name = 'RX Antenna Data' LIMIT 1), 'RAH', 'RAD', '5', '10', 'Y', false, 1050),
    ('460', 'Antenna Horizontal Beamwidth', (SELECT id FROM sfaf_field_categories WHERE name = 'RX Antenna Data' LIMIT 1), 'RBW', 'RAD,*EBWb ,*SBWb', '4', '10', 'Y', false, 1060),
    ('461', 'Antenna Vertical Beamwidth', (SELECT id FROM sfaf_field_categories WHERE name = 'RX Antenna Data' LIMIT 1), NULL, NULL, '3', '10', 'N', false, 1070),
    ('462', 'Antenna Orientation', (SELECT id FROM sfaf_field_categories WHERE name = 'RX Antenna Data' LIMIT 1), 'RAZ,RAA', 'RAZ,RAD', '3 3,3 3,3-3', '10', 'Y', false, 1080),
    ('463', 'Antenna Polarization', (SELECT id FROM sfaf_field_categories WHERE name = 'RX Antenna Data' LIMIT 1), 'RAP', 'RAP', '1', '10', 'Y', false, 1090),
    ('470', 'Space Station Noise', (SELECT id FROM sfaf_field_categories WHERE name = 'RX Antenna Data' LIMIT 1), NULL, 'N', 'SNT', '4', '10', false, 1100),
    ('471', 'Earth Station System Noise Temperature', (SELECT id FROM sfaf_field_categories WHERE name = 'RX Antenna Data' LIMIT 1), NULL, 'N', 'RNT', '4', '10', false, 1110),
    ('472', 'Equivalent Satellite Link Noise Temperature', (SELECT id FROM sfaf_field_categories WHERE name = 'RX Antenna Data' LIMIT 1), NULL, 'N', 'ENT', '4', '10', false, 1120),
    ('500', 'IRAC Notes', (SELECT id FROM sfaf_field_categories WHERE name = 'Supplementary Details' LIMIT 1), 'NTS', 'NTS', '4', '10', 'Y', false, 1130),
    ('501', 'Notes free-text Comments', (SELECT id FROM sfaf_field_categories WHERE name = 'Supplementary Details' LIMIT 1), 'NOT', '*NTSb', '35', '30', 'Y', false, 1140),
    ('502', 'Description of Requirement', (SELECT id FROM sfaf_field_categories WHERE name = 'Supplementary Details' LIMIT 1), NULL, 'N', 'GEN', '1440', '1', false, 1150),
    ('503', 'Agency Free-text Comments', (SELECT id FROM sfaf_field_categories WHERE name = 'Supplementary Details' LIMIT 1), 'AGN', '*AGNb', '35', '30', 'Y', false, 1160),
    ('504', 'FAS Agenda or OUS&P Comments', (SELECT id FROM sfaf_field_categories WHERE name = 'Supplementary Details' LIMIT 1), 'FAS', 'FAS', '72', '5', 'Y', false, 1170),
    ('506', 'Paired Frequency', (SELECT id FROM sfaf_field_categories WHERE name = 'Supplementary Details' LIMIT 1), 'PRD', '*PRDb', '11,10,12', '30', 'Y', false, 1180),
    ('511', 'Major Function Identifier', (SELECT id FROM sfaf_field_categories WHERE name = 'Supplementary Details' LIMIT 1), 'MFI', '*MFIb', '30', '1', 'Y', false, 1190),
    ('512', 'Intermediate Function Identifier', (SELECT id FROM sfaf_field_categories WHERE name = 'Supplementary Details' LIMIT 1), 'IFI', '*IFIb', '30', '1', 'Y', false, 1200),
    ('513', 'Detailed Function Identifier', (SELECT id FROM sfaf_field_categories WHERE name = 'Supplementary Details' LIMIT 1), 'DFI', '*DFIb', '30', '5', 'Y', false, 1210),
    ('520', 'Supplementary Details', (SELECT id FROM sfaf_field_categories WHERE name = 'Supplementary Details' LIMIT 1), 'SUP', 'SUP', '1080', '1', 'Y', false, 1220),
    ('521', 'Transition and Narrow Band Planning Data', (SELECT id FROM sfaf_field_categories WHERE name = 'Supplementary Details' LIMIT 1), 'TRN', '*TRNb', '8,13', '1', 'Y', false, 1230),
    ('530', 'Authorized Areas', (SELECT id FROM sfaf_field_categories WHERE name = 'Supplementary Details' LIMIT 1), 'XAR,RAR,ARB', '*ARTb, *ARRb, *ARBb b', '3,35', '30', 'Y', false, 1240),
    ('531', 'Authorized States', (SELECT id FROM sfaf_field_categories WHERE name = 'Supplementary Details' LIMIT 1), 'AST', '*LSTb,*LSR b,*LSBb,*ES Tb,*ESRb, *ESBb', '3,35', '6', 'Y', false, 1250),
    ('701', 'Frequency Action Officer', (SELECT id FROM sfaf_field_categories WHERE name = 'Other Assignment IDs' LIMIT 1), NULL, '*AGN,FAOb', '3', '1', 'Yl', false, 1260),
    ('702', 'Control/Request Number', (SELECT id FROM sfaf_field_categories WHERE name = 'Other Assignment IDs' LIMIT 1), NULL, '*AGN,CNOb', '15', '1', 'Yo', false, 1270),
    ('704', 'Type of Service', (SELECT id FROM sfaf_field_categories WHERE name = 'Other Assignment IDs' LIMIT 1), NULL, NULL, '1', '1', 'N', true, 1280),
    ('707', 'PACOM Complement/ FMSC Function Number', (SELECT id FROM sfaf_field_categories WHERE name = 'Other Assignment IDs' LIMIT 1), NULL, NULL, '8', '20', 'N', false, 1290),
    ('710', 'Host Country Docket Number', (SELECT id FROM sfaf_field_categories WHERE name = 'Other Assignment IDs' LIMIT 1), NULL, NULL, '35', '10', 'N', false, 1300),
    ('711', 'Aeronautical Service Range and Height', (SELECT id FROM sfaf_field_categories WHERE name = 'Other Assignment IDs' LIMIT 1), NULL, NULL, '6', '1', 'N', false, 1310),
    ('716', 'Usage Code', (SELECT id FROM sfaf_field_categories WHERE name = 'Other Assignment IDs' LIMIT 1), NULL, NULL, '1', '1', 'N', true, 1320),
    ('801', 'Coordination Data/Remarks', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '60', '20', 'N', false, 1330),
    ('803', 'Requestor Data', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, 'N', 'POC', '60', '1', false, 1340),
    ('804', 'Tuning Range/Tuning Increments', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '60', '30', 'N', false, 1350),
    ('805', 'Date Response Required', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '8', '1', 'N', false, 1360),
    ('806', 'Indication if Host Nominations are Acceptable', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '60', '10', 'N', false, 1370),
    ('807', 'Frequencies to be Deleted', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '60', '10', 'N', false, 1380),
    ('901', 'Record Status', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '1', '1', 'N', false, 1390),
    ('903', 'Proposal Status', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, 'N', 'CPS', '4', '20', false, 1400),
    ('904', 'Status Date', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, 'N', 'STD', '8', '20', false, 1410),
    ('905', 'Proposal Date Time Group', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '14', '1', 'N', false, 1420),
    ('906', 'Originator', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '66', '1', 'N', false, 1430),
    ('907', 'Validation Status', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '1', '1', 'N', false, 1440),
    ('910', 'Exercise Project', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '20', '1', 'N', false, 1450),
    ('911', 'Date of Last Transaction', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, 'N', 'DAT', '8', '1', false, 1460),
    ('924', 'Data Source Indicator', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '4', '1', 'N', false, 1470),
    ('926', 'Semi-Bandwidth', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '12', '1', 'N', false, 1480),
    ('927', 'Date of Entry', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '8', '1', 'N', false, 1490),
    ('928', 'Date of Receipt', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, NULL, NULL, NULL, false, 1500),
    ('952', 'IRAC Security Classification', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, 'CLA', '1', '1', 'Y', false, 1510),
    ('953', 'IRAC Declassification Date', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, 'CDD', '10', '1', 'Y', false, 1520),
    ('956', 'Agency Action Number', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), 'ACN', 'ACN', '10', '1', 'Y', false, 1530),
    ('957', 'Review Year', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), 'RYR', 'RYR', '4', '1', 'Yh', false, 1540),
    ('958', 'Routine Agenda Item', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), 'RTN', 'RTN', '1', '1', 'Y', false, 1550),
    ('959', 'Circuit Remarks', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), 'REM', 'REM', '40', '30', 'N', false, 1560),
    ('963', 'FCC File Number', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), 'FLN', '*FLNb', '22', '1', 'Yh', false, 1570),
    ('964', 'Tx Aircraft Altitude', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, 'XAD', '3', '10', 'N', false, 1580),
    ('965', 'Rx Aircraft Altitude', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, 'RAD', '3', '10', 'N', false, 1590),
    ('982', 'JCEOI Line Number', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '5', '1', 'N', false, 1600),
    ('983', 'JCEOI Master Net List Name', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '16', '1', 'N', false, 1610),
    ('984', 'Net Frequency Range', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '11-11', '1', 'N', false, 1620),
    ('985', 'Joint Restricted Frequency List (JRFL) Protection Code', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '1, 1/2', '1', 'N', false, 1630),
    ('986', 'Net Tactical Call Word', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '15', '1', 'N', false, 1640),
    ('987', 'Net Tactical Call Sign', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '3', '1', 'N', false, 1650),
    ('988', 'Net Tactical Air Designator (TAD)', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '5', '1', 'N', false, 1660),
    ('989', 'Net Color Word', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '16', '1', 'N', false, 1670),
    ('990', 'Net Color Number', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '2', '1', 'N', false, 1680),
    ('991', 'Net Restoral Priority', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '3', '1', 'N', false, 1690),
    ('992', 'Net Push Number', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '3', '1', 'N', false, 1700),
    ('993', 'Band Usage', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '1', '1', 'N', false, 1710),
    ('994', 'Check Sum', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '1', '1', 'N', false, 1720),
    ('995', 'COMSEC Keymat', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '15', '1', 'N', false, 1730),
    ('996', 'Circuit Type, Line Item, Group Category', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '8', '1', 'N', false, 1740),
    ('997', 'JCEOI Special Net Instructions', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '63', '1', 'N', false, 1750),
    ('998', 'Net Notes', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '3', '1', 'N', false, 1760),
    ('999', 'Guard Requirements', (SELECT id FROM sfaf_field_categories WHERE name = 'Additional Information' LIMIT 1), NULL, NULL, '20', '50', 'N', false, 1770);

-- =========================================================
-- sfaf_required_fields
-- =========================================================
CREATE TABLE IF NOT EXISTS sfaf_required_fields (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    field_number VARCHAR(10) NOT NULL,
    scope_type  VARCHAR(20) NOT NULL CHECK (scope_type IN ('global','agency','unified_command','majcom')),
    scope_value VARCHAR(100) NOT NULL DEFAULT '',
    created_by  UUID,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uix_sfaf_required_fields
    ON sfaf_required_fields(field_number, scope_type, scope_value);
